on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  inspect:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-rc-bullseye

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ginside
          POSTGRES_PASSWORD: ginside
          POSTGRES_DB: ginside
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        installer-parallel: true

    - name: Install app dependencies
      run: |
        poetry install

    - name: Lint
      run: poetry run python -m flake8 tests ginside

    - name: Test
      env:
        GINSIDE_DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
      run: poetry run python -m pytest --cov-report=xml
